# Generated by Django 5.2.3 on 2025-08-14 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_profile_bank_account_number_profile_bank_ifsc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="paid_By_User",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
