# Generated by Django 5.2.3 on 2025-08-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_paymentlog_paid_by_user_paymentlog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentlog",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error or failure reason, if any.", null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="full_response",
            field=models.JSONField(
                blank=True,
                help_text="Full Razorpay response for audit/debugging.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Payment method/type (e.g., card, upi, netbanking)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="signature",
            field=models.CharField(
                blank=True,
                help_text="Razorpay payment signature for verification.",
                max_length=255,
                null=True,
            ),
        ),
    ]
