# Generated by Django 5.2.3 on 2025-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_paymentlog_error_message_paymentlog_full_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
