# Generated by Django 5.2.3 on 2025-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_booking_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="num_properties",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
