# Generated by Django 5.2.3 on 2025-08-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_property_num_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="num_properties",
        ),
    ]
