# Generated by Django 5.2.3 on 2025-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_property_num_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
