# Generated by Django 5.2.3 on 2025-09-01 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_recentview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(
                blank=True,
                default="property_images/default.jpg",
                null=True,
                upload_to="property_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://via.placeholder.com/400x300?text=Property+Image",
                null=True,
            ),
        ),
    ]
