# Generated by Django 5.2.3 on 2025-09-01 20:47

import django.core.validators
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_property_image_alter_property_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="property",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=home.models.property_video_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "mov", "avi"])
                ],
            ),
        ),
    ]
