# Generated by Django 5.2.3 on 2025-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("paid", "Paid"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
    ]
