# Generated by Django 4.2.11 on 2026-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
